raw d3 charts with react initial commit
mozilla/distribution-viewer pull request #117
Opened 2016-10-07 19:28 UTC by spasovski

known issues:

- less pretty tooltips (these are blocked on the new string templates)
- details page needs the chart to be resized

2016-10-07 19:36 UTC, openjck commented
I notice this branch doesn't return a 404 when an invalid chart ID is loaded (for example, localhost:8000/chart/999/)

2016-10-07 20:45 UTC, spasovski commented
The 404 issue is weird locally since it doesn't work on any branch. Likely the django vs react routing.

2016-10-07 21:26 UTC, openjck commented
I get a 404 for http://localhost:8000/chart/999/ locally on master.

2016-10-07 22:18 UTC, openjck commented
Also, it appears the sidebar links don't work on this branch.

2016-10-07 22:19 UTC, openjck requested changes
Otherwise this looks good. I'll admit the raw D3 is a little over my head but I don't see any obvious problems and the charts look beautiful.

2016-10-07 22:19 UTC, openjck commented on distributionviewer/core/static/js/app/components/containers/chart-axis-container.js
> +    return (<ChartAxis axisType={this.props.axisType} />);
Total nitpick, but we don't technically need the parens for one-line JSX.

2016-10-07 22:19 UTC, openjck commented on distributionviewer/core/static/js/app/components/views/chart-hover.js
> +    let d = x0 - d0.x > d1.x - x0 ? d1 : d0;
After hovering over charts for a while, I get an error in console about `d1` being undefined. (Chrome instead says that `x` is undefined.)

2016-10-10 18:56 UTC, openjck requested changes
Looks good to me. Nothing major really aside from the two issues mentioned earlier. Just a few minor code style things I noticed.

2016-10-10 18:56 UTC, openjck commented on distributionviewer/core/static/js/app/components/containers/chart-hover-container.js
> +import ChartHover from '../views/chart-hover.js';
Nitpick, but we've been omitting the `.js` elsewhere.

2016-10-10 18:56 UTC, openjck commented on distributionviewer/core/static/js/app/components/containers/chart-line-container.js
> +                .y(d => {return props.yScale(d.y);});
We can omit the curly braces and the `return` statement since we're doing a one-line arrow function.

2016-10-10 18:56 UTC, openjck commented on distributionviewer/core/static/js/app/components/views/chart-list.js
> +            <div>
Do we need this `<div>`?

2016-10-10 19:15 UTC, openjck commented
I added a *TODO* section to the PR description with a couple of other small functionality things I noticed.

2016-10-13 18:10 UTC, closed without merging